### ISSUE TITLE
Tomcat Vaadin Page loading times not accurate

### ISSUE THREAD

**Issue by faxe1008** [bengadbois/pewpew#28]
I tested my Vaadin Page using your tool. I get an average response time of 50ms which can not be accurate since when opening the page with a browser I have about 2 seconds of waiting time, because vaadin uses ajax calls to generate site content it seems. Is there a way to configure a test so that it waits for the page to load completly?

**Comment by bengadbois** [comment]
Yes, that's a limitation for testing websites. It won't parse the html and request any js, css, image tags, etc. or execute any of the js (which may invoke other ajax requests). It just requests and measures the provided target such as `/index.html`.

**Comment by faxe1008** [comment]
Thats unfortunate. Otherwise this is a great tool 👍

**Comment by bengadbois** [comment]
If you need html parsing, you might want to check out https://github.com/JoeDog/siege

I'm going to close this issue for now, as it's currently out of scope of this project
