### ISSUE TITLE
The path of upload is wrong!Failed to make request: Post "http://192.168.0.136:8199/admin/rank/SelectRankList": dial tcp 192.168.0.136:8199: connectex: Only one usage of each socket address (protocol/network address/port) is normally permitted.

### ISSUE THREAD

**Issue by 54huige** [bengadbois/pewpew#51]
Failed to make request: Post "http://192.168.0.136:8199/admin/rank/SelectRankList": dial tcp 192.168.0.136:8199: connectex: Only one usage of each socket address (protocol/network address/port) is normally permitted.

The path of upload is wrong!

**Comment by bengadbois** [comment]
This doesn't seem related to this project
