### ISSUE TITLE
on the windows. run ".\pewpew.exe stress -X POST -n 50000 -c 1000 -t 3s -H "Accept-Encoding:gzip, Content-Type:application/json" http://192.168.0.136:9501"

### ISSUE THREAD

**Issue by 54huige** [bengadbois/pewpew#52]
**There are many wrong outputs!**

Failed to make request: Post "http://192.168.0.136:9501": dial tcp 192.168.0.136:9501: connectex: Only one usage of each socket address (protocol/network address/port) is normally permitted.
Failed to make request: Post "http://192.168.0.136:9501": dial tcp 192.168.0.136:9501: connectex: Only one usage of each socket address (protocol/network address/port) is normally permitted.
Failed to make request: Post "http://192.168.0.136:9501": dial tcp 192.168.0.136:9501: connectex: Only one usage of each socket address (protocol/network address/port) is normally permitted.
Failed to make request: Post "http://192.168.0.136:9501": dial tcp 192.168.0.136:9501: connectex: Only one usage of each socket address (protocol/network address/port) is normally permitted.
Failed to make request: Post "http://192.168.0.136:9501": dial tcp 192.168.0.136:9501: connectex: Only one usage of each socket address (protocol/network address/port) is normally permitted.
HTTP/1.1 200    318 B   88 ms   -> POST http://192.168.0.136:9501
HTTP/1.1 200    318 B   74 ms   -> POST http://192.168.0.136:9501

----Summary----

Timing
Mean query speed:     139 ms
Fastest query speed:  0 ms
Slowest query speed:  2447 ms
Mean RPS:             1277.07 req/sec
Total time:           30097 ms

Data Transferred
Mean query:      318 B
Largest query:   318 B
Smallest query:  318 B
Total:           12 MB

Response Codes
200: 38437 responses (100.00%)

**Comment by bengadbois** [comment]
Cannot recreate this issue. It looks like a port conflict error, so I'd suggest looking at what else is using various ports. Can you recreate using with simpler flags (e.g. without headers, default timeout, lower concurrency, total count, etc.)?

**Comment by bengadbois** [comment]
Closing due to no response from original author
