### ISSUE TITLE
Staggered/delayed requests

### ISSUE THREAD

**Issue by stashymane** [bengadbois/pewpew#57]
Currently, pewpew immediately bombs the specified URL with requests. With just a few concurrent requests this is somewhat undesirable - would be nice if it were possible to stagger request threads, i.e. given 5 connections and a delay of 5 seconds, also allow 1 second before each run is started for a gradual ramp-up.

**Comment by bengadbois** [comment]
This is definitely true for the `stress` mode. Have you found this to be an issue when running the `pewpew benchmark` command? Depending on the selected settings, may start multiple concurrent requests, but they will be spaced out per second.

**Comment by stashymane** [comment]
Benchmark does space the requests out, but if the load keeps increasing it'll eventually result in timeouts, as there's no limit to the amount of requests (as far as i've tested).
I'll admit this isn't a very common use-case, but shouldn't be too hard to implement :)

**Comment by bengadbois** [comment]
> if the load keeps increasing it'll eventually result in timeouts

This mimics real world (clients time out), so this is desired behavior. There is a `--timeout` flag which can be increased to arbitrarily long values if the default 10 seconds is too short.



I appreciate the suggestion, but I'm going to close this issue for a few reasons:

1. The benchmark command covers fix rate request testing. This may not exactly behave the way you like, but it works for many other users.
2. Loading up requests at the start of pewpew (both stress and benchmark modes) is desirable, as staggering would not be respecting the concurrency settings. For example, a user runs `pewpew stress -c 5 localhost:80` and the first 4 requests are not running at level of 5 concurrent requests, which isn't obvious to the user and may be misleading.
3. You can sort of do what you're looking for today by doing something like:
```bash
for i in $(seq 1 5)
do
  sleep 1 # stagger amount
  pewpew stress -c 1 localhost:80 & 
done
```


> shouldn't be too hard to implement :)

You're welcome to fork the project and add this change, it's MIT licensed. You'll want to modify the `RunStress` command in https://github.com/bengadbois/pewpew/blob/master/lib/stress.go.
