### ISSUE TITLE
Count failed requests in Summary

### ISSUE THREAD

**Issue by hmnd** [bengadbois/pewpew#58]
#### How do you create the issue, and how reproducible is it? (show the full command)
`pewpew stress` and `pewpew benchmark` don't show include failed requests in the Summary shown at the end. I'm testing a server that sometimes doesn't respond with response headers or takes too long doing so, and `pewpew` only shows a count of requests with a 200 response at the end.

In the example below, all the red canceled or deadline exceeded errors are not included in the Summary:
![image](https://github.com/bengadbois/pewpew/assets/12853597/a69045b0-5ffc-4f01-92a3-575bd6e257e7)

#### What version of pewpew are you running?
v1.0.0

#### Did you compile pewpew yourself, or use a prebuilt version?
Installed using `go install`

**Comment by bengadbois** [comment]
Included in https://github.com/bengadbois/pewpew/pull/59, and will get included in the next release

**Comment by hmnd** [comment]
Thank you so much @bengadbois!
